sudo: false
language: ruby

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10

env:
  matrix:
  - PYTHON=python
  - PYENV_VERSION=3.6 PYTHON=python

before_install:
  - gem update --system
  - gem update bundler

before_script:
  - pip install --user -r requirements.txt
  - PYENV_VERSION=3.6 pip3 install --user -r requirements.txt

matrix:
  allow_failures:
  - env: PYTHON=python  # Ignore failed on python 2.7
