sudo: false
language: ruby

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-all
      - python3-all-dev

env:
  matrix:
  - PYTHON=python
  - PYTHON=python3
  - LIBPYTHON=/opt/python/3.5.3/lib/libpython3.5m.so

before_install:
  - gem update --system
  - gem update bundler

before_script:
  - pip install --user -r requirements.txt
  - pip3 install --user -r requirements.txt

matrix:
  allow_failures:
  - env: PYTHON=python  # Ignore failed on python 2.7
