language: ruby
os: linux
dist: bionic

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10

before_install:
  - gem update --system
  - gem update bundler

jobs:
  allow_failures:
    - python: 2.7
  include:
    - name: 'Python 3.6 on Linux'
      python: 3.6
      before_script:
        - pip3 install --user -r requirements.txt
    - name: 'Python 2.7 on Linux'
      python: 2.7
      before_script:
        - pip install --user -r requirements.txt
